#pragma once
#ifndef _Marine_VesselParams_Header
#define _Marine_VesselParams_Header

#include <Marine_VesselParam_AM.hxx>
#include <Marine_VesselParam_Amax.hxx>
#include <Marine_VesselParam_APP.hxx>
#include <Marine_VesselParam_AUW.hxx>
#include <Marine_VesselParam_AW.hxx>
#include <Marine_VesselParam_AWL.hxx>
#include <Marine_VesselParam_B.hxx>
#include <Marine_VesselParam_BWL.hxx>
#include <Marine_VesselParam_CAM.hxx>
#include <Marine_VesselParam_CB.hxx>
#include <Marine_VesselParam_CM.hxx>
#include <Marine_VesselParam_CP.hxx>
#include <Marine_VesselParam_CVP.hxx>
#include <Marine_VesselParam_CWL.hxx>
#include <Marine_VesselParam_D.hxx>
#include <Marine_VesselParam_DISPM.hxx>
#include <Marine_VesselParam_DISPV.hxx>
#include <Marine_VesselParam_DWL.hxx>
#include <Marine_VesselParam_FPP.hxx>
#include <Marine_VesselParam_FUW.hxx>
#include <Marine_VesselParam_FWL.hxx>
#include <Marine_VesselParam_HEELANG.hxx>
#include <Marine_VesselParam_KB.hxx>
#include <Marine_VesselParam_LCB.hxx>
#include <Marine_VesselParam_LCF.hxx>
#include <Marine_VesselParam_LOA.hxx>
#include <Marine_VesselParam_LOS.hxx>
#include <Marine_VesselParam_LPP.hxx>
#include <Marine_VesselParam_LWL.hxx>
#include <Marine_VesselParam_MPP.hxx>
#include <Marine_VesselParam_T.hxx>
#include <Marine_VesselParam_TA.hxx>
#include <Marine_VesselParam_TF.hxx>
#include <Marine_VesselParam_TM.hxx>
#include <Marine_VesselParam_VCB.hxx>
#include <Marine_VesselParam_WETA.hxx>

#endif // !_Marine_VesselParams_Header
